name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build
        run: npm install && npm run build
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
